apiVersion: v1
kind: Service
metadata:
  name: users-backend-svc
  namespace: dev
spec:
  selector:
    app: users-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort