name: DEV Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  build:
    name: Build
    uses: ./.github/templates/build.yaml
  unit_test:
    name: Unit Test
    uses: ./.github/templates/unit-test.yaml
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [unit_test]
    steps:
      - name: Deploying
        run: echo "Deploying"
