name: PRD Pipeline
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    permissions: read-all
    uses: ./.github/workflows/build.template.yaml
  unit_test:
    name: Unit Test
    permissions: read-all
    needs: [build]
    uses: ./.github/workflows/unit-test.template.yaml
  code_analysis:
    name: Unit Test
    permissions: read-all
    needs: [unit_test]
    uses: ./.github/workflows/sonarqube.template.yaml
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [code_analysis]
    steps:
      - name: Deploying
        run: echo "Deploying"
