name: PRD Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    uses: ./.github/templates/build.template.yaml
  unit_test:
    name: Unit Test
    uses: ./.github/templates/unit-test.template.yaml
  code_analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    permissions: read-all
    needs: [unit_test]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [code_analysis]
    steps:
      - name: Deploying
        run: echo "Deploying"
